apiVersion: v1
kind: ConfigMap
metadata:
  name: ethiolearn-config
  namespace: ethiolearn
data:
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "http://ethiolearn.local"
  NEXT_PUBLIC_API_URL: "http://ethiolearn.local"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SMTP_HOST: "smtp.mailtrap.io"
  SMTP_PORT: "2525"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET_NAME: "ethio-learn-media"
---
apiVersion: v1
kind: Secret
metadata:
  name: ethiolearn-secrets
  namespace: ethiolearn
type: Opaque
stringData:
  # Kubernetes stringData allows placing raw text which K8s automatically base64 encodes on apply
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/ethiolearn?schema=public"
  JWT_SECRET: "ethiolearn_shared_sso_secret_key_12345"
  CHAPA_SECRET_KEY: "CHAPUBK_TEST-mockkey123"
  AWS_ACCESS_KEY_ID: "mock-key"
  AWS_SECRET_ACCESS_KEY: "mock-secret"
  SMTP_USER: "mockuser"
  SMTP_PASS: "mockpass"
