apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: ethiolearn
  labels:
    app: web
spec:
  replicas: 2 # high availability
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ethiolearn-web:latest # replace with actual docker registry tag in prod
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: ethiolearn-config
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: ethiolearn
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: web
